cr_subtopics_dict = {
    "fundamentals_of_credit_risk": [
        "Definition and sources of credit risk",
        "Insolvency, default, and bankruptcy",
        "Credit-risk-generating transactions",
        "Entities exposed to credit risk",
        "Motivations for taking and managing credit risk"
    ],
    "credit_governance": [
        "Three lines of defense",
        "Credit origination and approval process",
        "Governance principles (guidelines, skills, limits, oversight)",
        "Parameters of credit-sensitive transactions",
        "Credit committee role"
    ],
    "credit_risk_management": [
        "Lending and financing policy",
        "Exposure and concentration limits",
        "Credit facility allocation",
        "Asset classification",
        "Loan loss provisions and reserves",
        "Expected vs unexpected loss",
        "IFRS 9 expected loss",
        "Workout and write-off strategies",
        "Credit risk analysis",
        "Credit risk management capacity"
    ],
    "credit_capital_and_loss_modeling": [
        "Economic capital",
        "Probability of default (PD)",
        "Exposure at default (EAD)",
        "Loss rate / loss given default (LGD)",
        "Expected loss (EL)",
        "Unexpected loss (UL)",
        "Binomial default variance",
        "Credit loss distribution",
        "Challenges in quantifying credit risk"
    ],
    "credit_risk_modeling": [
        "CAMEL framework",
        "Risk-weighted assets",
        "Capital adequacy ratio",
        "Judgmental, empirical, and financial default models",
        "Merton model",
        "Distance to default",
        "CreditRisk+",
        "CreditMetrics",
        "Moody's KMV",
        "RAROC"
    ],
    "credit_scoring_and_rating": [
        "Credit scoring vs credit rating",
        "Through-the-cycle vs point-in-time ratings",
        "Development of scoring and rating models",
        "Rating agency methodologies",
        "Criticisms of rating agencies"
    ],
    "retail_credit_risk": [
        "Retail vs corporate credit risk",
        "Retail banking credit risks",
        "Credit scoring model types",
        "Mortgage credit assessment",
        "Cutoff scores, default rates, and loss rates",
        "Scorecard monitoring",
        "CAP and accuracy ratio",
        "Customer relationship cycle",
        "Risk-based pricing"
    ],
    "country_and_sovereign_risk": [
        "Sources of country risk",
        "Country risk measurement methods",
        "Foreign vs local currency default",
        "Consequences of sovereign default",
        "Sovereign default risk measures",
        "Sovereign ratings",
        "Limitations of sovereign ratings",
        "Credit ratings vs bond spreads vs CDS spreads"
    ],
    "default_probability_models": [
        "Agencies vs internal ratings",
        "Altman's Z-score",
        "Borrower rating and PD",
        "Rating migration matrix",
        "Marginal, conditional, and cumulative default probability",
        "Hazard rate",
        "Recovery rate",
        "CDS mechanics",
        "CDS spreads and hazard rates",
        "CDS-bond basis",
        "Historical vs market-implied default probabilities",
        "Real-world vs risk-neutral default probabilities",
        "Merton, Moody's KMV, and Kamakura models"
    ],
    "credit_var": [
        "Credit VaR",
        "Market VaR vs Credit VaR",
        "Rating transition matrices in Credit VaR",
        "Vasicek model under Basel IRB",
        "CreditRisk+",
        "CreditMetrics for Credit VaR",
        "Credit spread risk in Credit VaR"
    ],
    "portfolio_credit_risk": [
        "Default correlation",
        "Correlation-based portfolio models",
        "Single-factor credit portfolio model",
        "Beta and asset return correlation",
        "Joint default probability",
        "Simulation of joint defaults",
        "Granularity effects in Credit VaR"
    ],
    "credit_risk_in_derivatives": [
        "Credit risk of derivatives",
        "Credit valuation adjustment (CVA)",
        "Debt valuation adjustment (DVA)",
        "Default probability from credit spreads",
        "Credit risk mitigants",
        "Reduced-form vs structural correlation models",
        "Gaussian copula",
        "Credit VaR with Gaussian copula",
        "CreditMetrics approach for derivatives"
    ],
    "credit_derivatives": [
        "Credit derivatives overview",
        "Credit default swaps (CDS)",
        "Total return swaps",
        "Collateralized debt obligations (CDOs)",
        "CDS valuation with credit risk",
        "Default probabilities in CDS pricing",
        "Credit indices and fixed coupons",
        "CDS forwards and CDS options",
        "Synthetic CDO valuation",
        "Compound correlation",
        "Base correlation",
        "Alternative default correlation estimation"
    ],
    "counterparty_credit_risk_in_derivatives": [
        "Counterparty credit risk from derivatives",
        "Exchange-traded vs OTC derivatives",
        "Clearing process",
        "Collateralization in derivatives markets",
        "ISDA Master Agreement",
        "Credit derivatives as mitigants and sources of risk",
        "Central clearing and CCPs",
        "Margin requirements",
        "SPVs, DPCs, monolines, and CDPCs",
        "Challenges in modeling derivatives risk"
    ],
    "counterparty_risk_management": [
        "Counterparty risk vs lending risk",
        "Transactions with counterparty risk",
        "Institutions with counterparty risk exposure",
        "Credit exposure and migration",
        "Replacement cost and mark-to-market",
        "Default probability and recovery",
        "CVA vs credit limits",
        "Mitigation of counterparty risk",
        "Costs of OTC derivatives",
        "xVA components"
    ],
    "netting_and_closeout": [
        "ISDA Master Agreement purpose",
        "Netting and multilateral netting",
        "Close-out procedures",
        "Effectiveness of netting",
        "Termination provisions",
        "Trade compression",
        "Net notional exposure",
        "Termination events"
    ],
    "collateral_and_settlement": [
        "Collateral management rationale",
        "Credit Support Annex (CSA)",
        "Threshold, initial margin, MTA, rounding, haircuts",
        "Credit support amount calculation",
        "Valuation agent",
        "Collateral mechanics and collateral types",
        "Collateral dispute reconciliation",
        "Two-way vs one-way CSA",
        "Collateral linked to credit quality",
        "Funding, rehypothecation, and segregation",
        "Market, operational, liquidity, and funding risk from collateralization",
        "Regulatory capital requirements"
    ],
    "central_clearing": [
        "Central counterparty (CCP)",
        "Novation",
        "Netting, multilateral offset, and compression",
        "Margin and default funds",
        "CCP risk management",
        "Loss waterfall",
        "Default management of clearing members",
        "Bilateral vs central clearing",
        "Initial margin vs default fund",
        "Advantages and disadvantages of central clearing"
    ],
    "future_exposure_modeling": [
        "Expected mark-to-market",
        "Expected exposure",
        "Potential future exposure",
        "Expected positive and negative exposure",
        "Effective expected positive exposure",
        "Maximum exposure",
        "Exposure vs VaR characterization",
        "Drivers of exposure profile",
        "Collateral impact on exposure",
        "Exposure profiles of derivatives",
        "Payment frequency and exercise-date effects",
        "Aggregation and correlation effects",
        "Funding exposure vs credit exposure",
        "Remargining period, threshold, and MTA effects"
    ],
    "cva_and_wrong_way_risk": [
        "Motivation for pricing counterparty risk",
        "CVA",
        "CVA spread",
        "Impact of credit spreads and recovery on CVA",
        "DVA",
        "Bilateral CVA (BCVA)",
        "UCVA vs BCVA",
        "UDVA vs BCVA",
        "Incremental and marginal CVA",
        "Netting in CVA",
        "Collateralization in CVA",
        "Margin period of risk",
        "Wrong-way risk",
        "Right-way risk",
        "Wrong-way collateral",
        "Wrong-way risk in CCPs",
        "Wrong-way risk modeling approaches",
        "Central clearing implications for wrong-way risk"
    ],
    "stress_testing_counterparty_exposure": [
        "Current, peak, expected, and expected positive exposure",
        "CCR as credit risk and market risk",
        "Stress testing loan portfolios",
        "Stress testing derivative portfolios",
        "Stressed expected loss vs stress loss",
        "Stress testing CVA",
        "Stressed CVA",
        "Stress testing DVA",
        "Pitfalls in CCR stress testing"
    ],
    "structured_credit_risk": [
        "Structured credit products",
        "Tranching",
        "Credit loss distribution in securitization",
        "Waterfall structure",
        "Participants in securitization",
        "Conflicts of interest in securitization",
        "Interim cashflow calculations",
        "Excess spread",
        "Overcollateralization account",
        "Cash flow tests for securitizations",
        "Simulation of tranche credit losses",
        "Effect of default probabilities and correlations",
        "Tranche default sensitivities",
        "Risk factors in structured products",
        "Implied correlation",
        "Motivations for using structured credit products"
    ],
    "securitization": [
        "Securitization process",
        "Participants in securitization",
        "Over-collateralization",
        "First-loss and equity pieces",
        "Cash waterfall",
        "Trust vs SPV issuance structures",
        "Amortizing, revolving, and master trust SPVs",
        "Benefits of securitization",
        "Credit enhancements",
        "Performance analysis tools for securitized structures",
        "Delinquency ratio",
        "Default ratio",
        "Monthly payment rate (MPR)",
        "Debt service coverage ratio (DSCR)",
        "Weighted average coupon (WAC)",
        "Weighted average maturity (WAM)",
        "Weighted average life (WAL)",
        "Prepayment forecasting",
        "Constant prepayment rate (CPR)",
        "PSA rate"
    ]
}


cr_broad_topics = [
    "Credit analysis",
    "Default risk: quantitative methodologies",
    "Expected and unexpected loss",
    "Credit VaR",
    "Counterparty risk",
    "Credit derivatives",
    "Structured finance and securitization"
]